name: "fetch lark docs (manual)"
on: workflow_dispatch

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
    - name: get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d')"
    - name: set up Environment
      uses: actions/setup-node@v4.0.1
    - name: checkout repo
      uses: actions/checkout@v4
    - name: fetch docs
      run: |
        yarn
        npx docusaurus report-to-lark -m "ðŸ”¥ Someone manually triggered the workflow to fetch lark docs."
        npx docusaurus report-to-lark -m "ðŸ”¥ Start building global docs..."
        npx docusaurus fetch-lark-docs -man guides -tar zilliz.saas
        npx docusaurus fetch-lark-docs -man guides -tar zilliz.saas -post
        npx docusaurus fetch-lark-docs -man guides -tar zilliz.paas -skipS
        npx docusaurus fetch-lark-docs -man guides -tar zilliz.paas -post
        npx docusaurus fetch-lark-docs -man python -src-only
        npx docusaurus fetch-lark-docs -man pymilvus25 -tar zilliz
        npx docusaurus fetch-lark-docs -man pymilvus25 -tar zilliz -post
        npx docusaurus fetch-lark-docs -man javaV1 -tar zilliz
        npx docusaurus fetch-lark-docs -man javaV1 -tar zilliz -post
        npx docusaurus fetch-lark-docs -man javaV2 -tar zilliz
        npx docusaurus fetch-lark-docs -man javaV2 -tar zilliz -post
        npx docusaurus fetch-lark-docs -man node -src-only
        npx docusaurus fetch-lark-docs -man nodejs25 -tar zilliz
        npx docusaurus fetch-lark-docs -man nodejs25 -tar zilliz -post
        npx docusaurus fetch-apifox-docs -s plugins/apifox-docs/meta/openapi.json
        npx docusaurus fetch-lark-docs -man guidesJapanese -tar zilliz.saas
        npx docusaurus fetch-lark-docs -man guidesJapanese -tar zilliz.saas -post
        npx docusaurus fetch-lark-docs -man guidesJapanese -tar zilliz.paas -skipS
        npx docusaurus fetch-lark-docs -man guidesJapanese -tar zilliz.paas -post
      env:
        APP_ID: ${{ secrets.APP_ID }}
        APP_SECRET: ${{ secrets.APP_SECRET }}
        FEISHU_HOST: ${{ vars.FEISHU_HOST }}
        SPACE_ID: ${{ secrets.SPACE_ID }}
        FIGMA_API_KEY: ${{ secrets.FIGMA_API_KEY }}
    - name: build docsite
      run: |
        npx docusaurus report-to-lark -m "ðŸ”¥ All docs fetched! Building docs..."
        npm run build
      env:
        APP_ID: ${{ secrets.APP_ID }}
        APP_SECRET: ${{ secrets.APP_SECRET }}
        FEISHU_HOST: ${{ vars.FEISHU_HOST }}
    - name: link checks
      env:
        TOKEN: ${{ secrets.ACTION_TOKEN }}
        APP_ID: ${{ secrets.APP_ID }}
        APP_SECRET: ${{ secrets.APP_SECRET }}
        FEISHU_HOST: ${{ vars.FEISHU_HOST }}
      run: |
        npx docusaurus report-to-lark -m "ðŸ”¥ Docs built! Checking links..."
        curl -H "Authorization: token $TOKEN" https://raw.githubusercontent.com/zilliztech/zilliz-cloud-client/release_2.0.0/packages/CommonService/client/src/consts/Link.ts -o plugins/link-checks/meta/Link.ts
        npx docusaurus link-checks
    - name: commit to dev-multi-lingua
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        branch: dev
        create_branch: true
        push_options: --force
  failure:
    needs: fetch
    runs-on: ubuntu-latest
    if: failure()
    steps:
    - name: set up Environment
      uses: actions/setup-node@v4.0.1
    - name: checkout repo
      uses: actions/checkout@v4
    - name: report failure
      run : |
        yarn
        npx docusaurus report-to-lark -m "ðŸ”¥ Build failed! Please check the logs."
      env:
        APP_ID: ${{ secrets.APP_ID }}
        APP_SECRET: ${{ secrets.APP_SECRET }}
        FEISHU_HOST: ${{ vars.FEISHU_HOST }}
  success:
    needs: fetch
    runs-on: ubuntu-latest
    if: success()
    steps:
    - name: set up Environment
      uses: actions/setup-node@v4.0.1
    - name: checkout repo
      uses: actions/checkout@v4
    - name: report success
      run : |
        yarn
        npx docusaurus report-to-lark -m "ðŸ”¥ Build succeeded! You can build docs on Jenkins now."  
      env:
        APP_ID: ${{ secrets.APP_ID }}
        APP_SECRET: ${{ secrets.APP_SECRET }}
        FEISHU_HOST: ${{ vars.FEISHU_HOST }}
